"""Free-form temporal DAG generation for MAS emperor planning."""

from __future__ import annotations

import json
import re
from collections import Counter
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from statistics import fmean
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator

from exp_graph.llm.base import LLMClient, LLMResponse
from exp_graph.mas.motifs import score_spec_by_motifs
from exp_graph.mas.operators import compose_protocol_from_operators
from exp_graph.mas.planner import EmperorPlanner
from exp_graph.mas.role_llm import (
    create_role_llm_client,
    resolve_role_llm_config,
    role_llm_summary,
)
from exp_graph.mas.schemas import MASPlan, MASRuntimeConfig, PlannerRequest, SkillCard
from exp_graph.mas.skill_bank import SkillBank
from exp_graph.mas.topology_equivalence import (
    fingerprint_protocol_spec,
    protocol_metadata_with_fingerprint,
)
from exp_graph.protocols import ProtocolGraphSpec, ProtocolStepSpec
from exp_graph.runner import ProtocolExperimentResult, ProtocolRunner, ProtocolRunnerConfig
from exp_graph.tasks import CountFrequencyTaskAdapter


GraphSearchMode = Literal["single", "topk"]


class GeneratedGraphStep(BaseModel):
    """One simultaneous communication round generated by the emperor."""

    description: str = ""
    edges: list[tuple[int, int]] = Field(default_factory=list)
    operator_hint: str = "llm_generated"

    @field_validator("edges", mode="before")
    @classmethod
    def normalize_edges(cls, value: object) -> list[tuple[int, int]]:
        if value is None:
            return []
        if not isinstance(value, list):
            raise ValueError("edges must be a list")
        edges: list[tuple[int, int]] = []
        for item in value:
            if not isinstance(item, (list, tuple)) or len(item) != 2:
                raise ValueError("each edge must be a [src, dst] pair")
            edges.append((int(item[0]), int(item[1])))
        return edges


class GeneratedGraphPlan(BaseModel):
    """Structured JSON topology candidate produced by the emperor."""

    candidate_id: str = "candidate_0"
    name: str = "generated_temporal_dag"
    graph_type: str = "temporal_dag"
    n_agents: int
    steps: list[GeneratedGraphStep] = Field(default_factory=list)
    selected_primary: int | None = None
    rationale: str = ""
    expected_tradeoff: dict[str, object] = Field(default_factory=dict)
    fallback_topology: str | None = None


class GraphValidationOptions(BaseModel):
    """Hard constraints for generated topology candidates."""

    n_agents: int
    max_steps: int = 4
    max_messages: int = 32
    max_receiver_fan_in: int = 4
    repair_attempts: int = 1


class GraphValidationResult(BaseModel):
    """Validation/repair status for one generated graph."""

    valid: bool
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    repair_notes: list[str] = Field(default_factory=list)


class GraphCandidateRecord(BaseModel):
    """Serializable artifact for one free-graph candidate."""

    candidate_id: str
    status: str
    graph_plan: dict[str, object] | None = None
    protocol_spec: dict[str, object] | None = None
    validation_errors: list[str] = Field(default_factory=list)
    validation_warnings: list[str] = Field(default_factory=list)
    repair_notes: list[str] = Field(default_factory=list)
    protocol_steps: int = 0
    protocol_messages: int = 0
    selected_primary: int | None = None
    probe_scores: list[dict[str, object]] = Field(default_factory=list)
    objective_score: float | None = None
    score_mode: str = "objective"
    topology_equivalence_hash: str | None = None
    exact_execution_hash: str | None = None
    canonical_temporal_edges: list[tuple[int, int, int]] = Field(default_factory=list)
    duplicate_of_candidate_id: str | None = None


class FreeGraphPlanningResult(BaseModel):
    """Output from V1/V2 free graph planning."""

    plan: MASPlan
    candidates: list[GraphCandidateRecord] = Field(default_factory=list)
    selected_candidate_id: str | None = None
    fallback_reason: str | None = None
    raw_responses: list[str] = Field(default_factory=list)


@dataclass
class _CandidateState:
    graph: GeneratedGraphPlan
    record: GraphCandidateRecord
    spec: ProtocolGraphSpec | None = None
    generation_index: int = 0


def plan_free_graph(
    *,
    request: PlannerRequest,
    runtime: MASRuntimeConfig,
    skill_bank: SkillBank,
    seed: int,
    task_adapter: CountFrequencyTaskAdapter,
    output_dir: Path,
    llm_client: LLMClient | None = None,
) -> FreeGraphPlanningResult:
    """Generate, validate, optionally probe-evaluate, and select a graph plan."""
    options = GraphValidationOptions(
        n_agents=request.n_agents,
        max_steps=runtime.graph_max_steps,
        max_messages=runtime.graph_max_messages,
        max_receiver_fan_in=runtime.graph_max_receiver_fan_in,
        repair_attempts=runtime.graph_repair_attempts,
    )
    # Pull a short task description from the adapter (duck-typed; CF adapters
    # don't define it -> None, and the CF prompt branch ignores it anyway) so the
    # emperor sees the ACTUAL task instead of hardcoded count_frequency notes.
    _describe = getattr(task_adapter, "describe_task", None)
    task_brief: str | None = None
    if callable(_describe):
        try:
            task_brief = _describe()
        except Exception:
            task_brief = None
    raw_responses: list[str] = []
    try:
        graphs, raw_responses = _generate_graph_candidates(
            request=request,
            runtime=runtime,
            skill_bank=skill_bank,
            options=options,
            llm_client=llm_client,
            task_brief=task_brief,
        )
        candidates = _validate_and_compile_candidates(graphs, options)
        representative_candidates = _dedupe_equivalent_candidates(candidates)
        valid_states = [
            state
            for state in representative_candidates
            if state.record.status in {"valid", "repaired"} and state.spec is not None
        ]
        if not valid_states:
            raise ValueError("no valid generated graph candidates")
        if runtime.graph_search_mode == "topk" and runtime.graph_validation_seeds:
            _evaluate_candidates(
                states=valid_states,
                request=request,
                runtime=runtime,
                seed=seed,
                task_adapter=task_adapter,
                output_dir=output_dir / "graph_candidate_eval",
            )
            valid_states.sort(
                key=lambda state: state.record.objective_score
                if state.record.objective_score is not None
                else float("-inf"),
                reverse=True,
            )
        selected = _select_candidate(valid_states, runtime)
        selected.record.status = "selected"
        plan = _mas_plan_from_graph(selected.graph, selected.spec)
        records = [state.record for state in candidates]
        _write_graph_artifacts(
            output_dir=output_dir,
            records=records,
            selected=selected.record,
            raw_responses=raw_responses,
            top_k=max(1, runtime.graph_top_k),
        )
        return FreeGraphPlanningResult(
            plan=plan,
            candidates=records,
            selected_candidate_id=selected.record.candidate_id,
            raw_responses=raw_responses,
        )
    except Exception as exc:
        fallback = _fallback_operator_plan(request, skill_bank, str(exc))
        result = FreeGraphPlanningResult(
            plan=fallback,
            fallback_reason=str(exc),
            raw_responses=raw_responses,
        )
        _write_graph_artifacts(
            output_dir=output_dir,
            records=[],
            selected=None,
            raw_responses=raw_responses,
            fallback_reason=str(exc),
            top_k=max(1, runtime.graph_top_k),
        )
        return result


def validate_graph_plan(
    graph: GeneratedGraphPlan,
    options: GraphValidationOptions,
) -> GraphValidationResult:
    """Validate a generated temporal DAG candidate."""
    errors: list[str] = []
    warnings: list[str] = []
    if graph.graph_type != "temporal_dag":
        errors.append("graph_type must be temporal_dag")
    if graph.n_agents != options.n_agents:
        errors.append(
            f"n_agents mismatch: graph={graph.n_agents} expected={options.n_agents}"
        )
    if not graph.steps:
        errors.append("graph must contain at least one step")
    if len(graph.steps) > options.max_steps:
        errors.append(f"graph exceeds max_steps={options.max_steps}")
    total_messages = sum(len(step.edges) for step in graph.steps)
    if total_messages > options.max_messages:
        errors.append(f"graph exceeds max_messages={options.max_messages}")
    final_receivers: set[int] = set()
    for step_idx, step in enumerate(graph.steps):
        seen: set[tuple[int, int]] = set()
        fan_in: Counter[int] = Counter()
        for src, dst in step.edges:
            edge = (int(src), int(dst))
            if src == dst:
                errors.append(f"step {step_idx} contains self-loop {edge}")
            if src < 0 or dst < 0 or src >= options.n_agents or dst >= options.n_agents:
                errors.append(f"step {step_idx} contains invalid agent id {edge}")
            if edge in seen:
                warnings.append(f"step {step_idx} contains duplicate edge {edge}")
            seen.add(edge)
            fan_in[dst] += 1
            final_receivers.add(dst)
        overloaded = [
            receiver
            for receiver, count in fan_in.items()
            if count > options.max_receiver_fan_in
        ]
        if overloaded:
            errors.append(
                f"step {step_idx} exceeds max_receiver_fan_in for {overloaded}"
            )
    if not final_receivers:
        errors.append("graph has no receiver / answer holder")
    if graph.selected_primary is not None:
        if graph.selected_primary < 0 or graph.selected_primary >= options.n_agents:
            errors.append("selected_primary must be a valid agent id")
    else:
        warnings.append("selected_primary missing")
    if graph.selected_primary is not None and final_receivers:
        _add_reachability_warnings(graph, warnings)
    return GraphValidationResult(valid=not errors, errors=errors, warnings=warnings)


def repair_graph_plan(
    graph: GeneratedGraphPlan,
    options: GraphValidationOptions,
) -> tuple[GeneratedGraphPlan, list[str]]:
    """Apply deterministic repair to common graph-generation mistakes."""
    notes: list[str] = []
    repaired_steps: list[GeneratedGraphStep] = []
    message_budget = options.max_messages
    for step_idx, step in enumerate(graph.steps[: options.max_steps]):
        seen: set[tuple[int, int]] = set()
        fan_in: Counter[int] = Counter()
        edges: list[tuple[int, int]] = []
        for src, dst in step.edges:
            edge = (int(src), int(dst))
            if src == dst:
                notes.append(f"removed self-loop {edge} at step {step_idx}")
                continue
            if src < 0 or dst < 0 or src >= options.n_agents or dst >= options.n_agents:
                notes.append(f"removed invalid edge {edge} at step {step_idx}")
                continue
            if edge in seen:
                notes.append(f"deduped edge {edge} at step {step_idx}")
                continue
            if fan_in[dst] >= options.max_receiver_fan_in:
                notes.append(f"removed fan-in overflow edge {edge} at step {step_idx}")
                continue
            if message_budget <= 0:
                notes.append("trimmed edges beyond max_messages")
                continue
            seen.add(edge)
            fan_in[dst] += 1
            edges.append(edge)
            message_budget -= 1
        if edges:
            repaired_steps.append(
                GeneratedGraphStep(
                    description=step.description,
                    edges=edges,
                    operator_hint=step.operator_hint,
                )
            )
    if len(graph.steps) > options.max_steps:
        notes.append(f"trimmed steps beyond max_steps={options.max_steps}")
    selected = graph.selected_primary
    final_receivers = [
        dst for step in repaired_steps for _src, dst in step.edges
    ]
    if selected is None or selected < 0 or selected >= options.n_agents:
        selected = final_receivers[-1] if final_receivers else None
        notes.append(f"repaired selected_primary={selected}")
    return (
        graph.model_copy(
            update={
                "n_agents": options.n_agents,
                "steps": repaired_steps,
                "selected_primary": selected,
            }
        ),
        notes,
    )


def compile_generated_graph(
    graph: GeneratedGraphPlan,
    options: GraphValidationOptions,
) -> ProtocolGraphSpec:
    """Compile a validated generated graph to ProtocolGraphSpec."""
    validation = validate_graph_plan(graph, options)
    if not validation.valid:
        raise ValueError("; ".join(validation.errors))
    spec = ProtocolGraphSpec(
        name=graph.name,
        n_agents=options.n_agents,
        steps=[
            ProtocolStepSpec(
                transmissions=step.edges,
                description=step.description or f"{graph.name}: step {idx}",
                operator=step.operator_hint or "llm_generated",
            )
            for idx, step in enumerate(graph.steps)
        ],
        operators=["llm_generate_dag"],
        metadata={
            "graph_type": graph.graph_type,
            "generated_graph": True,
            "candidate_id": graph.candidate_id,
            "selected_primary": graph.selected_primary,
            "max_steps": options.max_steps,
            "max_messages": options.max_messages,
            "max_receiver_fan_in": options.max_receiver_fan_in,
            "fallback_topology": graph.fallback_topology,
        },
    )
    return spec.model_copy(
        update={
            "metadata": {
                **spec.metadata,
                **protocol_metadata_with_fingerprint(spec),
            }
        }
    )


def build_free_graph_prompt(
    *,
    request: PlannerRequest,
    skills: list[SkillCard],
    avoid_skills: list[SkillCard] | None = None,
    options: GraphValidationOptions,
    num_candidates: int,
    task_brief: str | None = None,
) -> str:
    """Build the JSON-only prompt for free DAG generation."""
    last_agent_id = request.n_agents - 1
    is_cf = request.task_family == "count_frequency"
    if is_cf:
        final_information_flow = (
            "For count_frequency, every source agent should have a temporal "
            "path to selected_primary so one final holder can contain all "
            "partial counts."
        )
    else:
        _brief_suffix = f" ({task_brief})" if task_brief else ""
        final_information_flow = (
            "Every source agent must have a temporal path to selected_primary so "
            "the final holder receives all information needed to compute the global "
            f"answer for this task{_brief_suffix}."
        )
    payload = {
        "role": (
            "You are a multi-agent system topology architect. Your job is to "
            "design explicit communication structures for an LLM-based MAS, not "
            "to answer the task and not to choose a named template."
        ),
        "mission": (
            "Design temporal communication topologies from scratch for this exact "
            "n_agents and objective. Output concrete per-round directed edges that "
            "define who sends their current belief artifact to whom."
        ),
        "task": (
            "Return a json object with a candidates array. Each candidate must be "
            "a complete temporal_dag communication protocol with explicit steps "
            "and edges. Here DAG means the time-expanded execution graph, so "
            "agent-level feedback across steps is valid. Do not solve the task, "
            "and do not merely name or copy an existing topology template."
        ),
        "request": request.model_dump(mode="json"),
        "graph_constraints": options.model_dump(mode="json"),
        "num_candidates": num_candidates,
        "edge_semantics": {
            "edge": "[src, dst] means dst receives src's current answer artifact after the previous step.",
            "step": "All edges inside one step are simultaneous; a receiver cannot use another receiver's same-step update until the next step.",
            "fan_out": "One src may send the same current outbox to multiple dst receivers in the same step; each edge counts as one message but does not create an extra source update.",
            "feedback": "Static agent-level cycles are allowed when they occur over time, such as step0 0->1 followed by step1 1->0.",
            "merge": (
                "Receivers merge non-overlapping source coverage from incoming "
                "artifacts. A good topology makes provenance easy to preserve and "
                "avoids duplicate counting."
            ),
            "final_information_flow": final_information_flow,
        },
        "topology_design_contract": {
            "agent_id_range": f"0..{last_agent_id}",
            "selected_primary": (
                f"Use an integer in [0, {last_agent_id}]. The default sink is "
                f"{last_agent_id}, but another explicit agent id is allowed when "
                "the edge plan justifies it."
            ),
            "coverage": (
                "Do not isolate agents. Every agent's local shard evidence should "
                "eventually reach the selected primary or reach all final voters "
                "with identical complete coverage."
            ),
            "cost_accuracy_tradeoff": (
                "Balanced objective means low message count is useful only when "
                "the graph still preserves global coverage and arithmetic merge "
                "clarity."
            ),
            "free_design_requirement": (
                "Invent the edge schedule directly for this n_agents. Use "
                "structural attributes such as staged aggregation, bounded "
                "receiver fan-in, explicit sink placement, audit/repair edges, "
                "provenance flow, and temporal reachability. The output must be "
                "the actual DAG edges, not a template label."
            ),
        },
        "candidate_diversity_requirements": [
            "If num_candidates > 1, produce structurally different edge schedules rather than renaming the same graph.",
            "Vary the sink choice, fan-in pattern, or audit/repair edge placement when it helps the objective.",
            "Each candidate must independently satisfy graph_constraints.",
        ],
        "operator_hints": [
            "bounded fan-in aggregation",
            "staged local merge",
            "explicit sink placement",
            "audit edge for provenance check",
            "coverage repair relay",
            "budget-aware partial aggregation",
        ],
        "skill_evidence": [_skill_context(skill) for skill in skills[:6]],
        "avoid_or_counterexample_skills": [
            _skill_context(skill) for skill in (avoid_skills or [])[:6]
        ],
        "skill_usage_rules": [
            "Use design_insights, structure_features, and operation_recommendations from skills as concrete design operations, not as topology names to copy blindly.",
            "Prioritize design_insights.operation_recommendations when deciding which edges, fan-in limits, sink choices, audit/provenance paths, or condition buckets to preserve, mutate, avoid, or validate.",
            "If a skill includes organization_policy.protocol_spec, treat it as an executable reference edge schedule; preserve or deliberately improve its coverage, sink, and fan-in properties.",
            "Respect condition buckets in skill triggers; do not generalize a skill outside its n_agents or array_size bucket without evidence.",
            "When a skill says preserve a selected_primary sink, emit that sink explicitly in selected_primary and maintain temporal reachability to it.",
            "Treat avoid_or_counterexample_skills as negative constraints; do not reproduce their edge schedules or failure patterns for the same condition bucket.",
            "In each candidate rationale, name the design insight or operation recommendation being preserved, mutated, avoided, or validated.",
        ],
        "required_json_shape": {
            "candidates": [
                {
                    "candidate_id": "candidate_0",
                    "name": "tree_reduce_to_sink",
                    "graph_type": "temporal_dag",
                    "n_agents": request.n_agents,
                    "selected_primary": last_agent_id,
                    "steps": [
                        {
                            "description": "what this round does",
                            "operator_hint": "bounded_fan_in_aggregation",
                            "edges": [[0, 1], [2, 3]],
                        }
                    ],
                    "rationale": "short evidence-grounded explanation",
                    "expected_tradeoff": {"accuracy": "medium", "cost": "low"},
                    "fallback_topology": "explicit_temporal_dag",
                }
            ]
        },
        "rules": [
            "Return one json object only.",
            "Do not wrap the answer in schema, output_schema, markdown, or prose.",
            "Use agent ids from 0 to n_agents-1 only.",
            f"selected_primary must be an explicit integer from 0 to {last_agent_id}; do not write an expression such as n_agents-1.",
            "Never create self-loops.",
            "Keep total messages and steps within graph_constraints.",
            "A step is simultaneous; temporal order is the order of steps.",
            "Same-step bidirectional edges and multi-recipient fan-out are allowed when they help coverage.",
            "Prefer novel but executable DAGs with clear information flow, not just topology names.",
            "Set 'name' to a short snake_case label describing THIS DAG's actual structure (e.g. tree_reduce_to_sink, staged_pair_gather, audited_star_sink); never output the literal placeholder 'short_snake_case_name'.",
            "Reject your own candidate mentally if any source agent lacks a temporal path to the selected_primary.",
        ],
    }
    if is_cf:
        payload["count_frequency_design_notes"] = [
            "The task is sharded frequency counting. Correctness needs lossless propagation of each agent's local count map.",
            "A reducer that receives partials in one step should be the sender in a later step when forwarding aggregated evidence.",
            "Sparse graphs are acceptable only when their temporal paths still cover all source agents.",
            "Avoid final states where most agents still hold only local or pairwise partial counts.",
        ]
    else:
        payload["task_design_notes"] = [
            (f"Task: {task_brief}" if task_brief else f"Task family: {request.task_family}."),
            "Each agent holds only a private shard; design the structure so the selected final holder receives enough information to compute the correct GLOBAL answer for THIS task.",
            "Correctness needs lossless propagation: every source agent needs a temporal path to selected_primary; avoid final states where the holder still lacks full coverage.",
            "Sparse graphs are acceptable only when their temporal paths still cover all source agents.",
        ]
    return json.dumps(payload, ensure_ascii=True, indent=2, sort_keys=True)


def _generate_graph_candidates(
    *,
    request: PlannerRequest,
    runtime: MASRuntimeConfig,
    skill_bank: SkillBank,
    options: GraphValidationOptions,
    llm_client: LLMClient | None,
    task_brief: str | None = None,
) -> tuple[list[GeneratedGraphPlan], list[str]]:
    count = max(1, runtime.num_graph_candidates)
    positive_skills = skill_bank.retrieve(request)
    seeded = _skill_seeded_graph_candidates(
        request=request,
        skills=positive_skills,
    )
    remaining_count = max(0, count - len(seeded))
    emperor_llm = resolve_role_llm_config(runtime, "emperor")
    if emperor_llm.platform == "fake":
        return [*seeded, *_fake_graph_candidates(request, remaining_count)], []
    if remaining_count == 0:
        return seeded, []
    client = llm_client or create_role_llm_client(runtime, "emperor")
    prompt = build_free_graph_prompt(
        request=request,
        skills=positive_skills,
        avoid_skills=skill_bank.retrieve_avoid(request),
        options=options,
        num_candidates=remaining_count,
        task_brief=task_brief,
    )
    response = client.complete(
        prompt,
        model_name=emperor_llm.model_name,
        temperature=emperor_llm.temperature,
    )
    candidates = parse_graph_candidates_response(
        response.text,
        n_agents=request.n_agents,
        expected_count=remaining_count,
    )
    return [*seeded, *candidates], [response.text]


def _skill_seeded_graph_candidates(
    *,
    request: PlannerRequest,
    skills: list[SkillCard],
) -> list[GeneratedGraphPlan]:
    graphs: list[GeneratedGraphPlan] = []
    seen: set[str] = set()
    for skill in skills[:6]:
        spec_data = skill.organization_policy.get("protocol_spec")
        if not isinstance(spec_data, dict) or not spec_data.get("steps"):
            continue
        try:
            spec = ProtocolGraphSpec.model_validate(spec_data)
        except Exception:
            continue
        if spec.n_agents != request.n_agents:
            continue
        graph = _graph_from_skill_protocol(skill, spec)
        digest = fingerprint_protocol_spec(spec).topology_equivalence_hash
        if digest in seen:
            continue
        seen.add(digest)
        graphs.append(graph)
        if len(graphs) >= 3:
            break
    return graphs


def _graph_from_skill_protocol(
    skill: SkillCard,
    spec: ProtocolGraphSpec,
) -> GeneratedGraphPlan:
    selected = spec.metadata.get("selected_primary")
    return GeneratedGraphPlan(
        candidate_id=f"skill_{_safe_candidate_id(skill.skill_id)}",
        name=spec.name or _safe_candidate_id(skill.skill_id),
        graph_type=str(spec.metadata.get("graph_type") or "temporal_dag"),
        n_agents=spec.n_agents,
        selected_primary=_optional_int(selected),
        steps=[
            GeneratedGraphStep(
                description=step.description,
                edges=step.transmissions,
                operator_hint=step.operator or "skill_replay",
            )
            for step in spec.steps
        ],
        rationale=f"Replay executable DAG stored in skill {skill.skill_id}.",
        expected_tradeoff=skill.expected_tradeoff,
        fallback_topology=(
            str(spec.metadata["fallback_topology"])
            if spec.metadata.get("fallback_topology") is not None
            else None
        ),
    )


def _safe_candidate_id(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]+", "_", value).strip("_")[:80] or "skill"


def _optional_int(value: object) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _graph_digest(graph: GeneratedGraphPlan) -> str:
    return json.dumps(
        [
            {
                "edges": step.edges,
                "operator_hint": step.operator_hint,
            }
            for step in graph.steps
        ],
        sort_keys=True,
        separators=(",", ":"),
    )


def parse_graph_candidates_response(
    text: str,
    *,
    n_agents: int,
    expected_count: int = 1,
) -> list[GeneratedGraphPlan]:
    """Parse an LLM response into generated graph candidates."""
    data = _loads_json_object(text)
    if "output_schema" in data or "required_json_shape" in data:
        raise ValueError("LLM echoed the graph schema instead of candidates")
    raw_candidates = data.get("candidates")
    if raw_candidates is None:
        raw_candidates = [data]
    if not isinstance(raw_candidates, list):
        raise ValueError("graph response must contain a candidates list")
    graphs = []
    for idx, item in enumerate(raw_candidates[: max(1, expected_count)]):
        if not isinstance(item, dict):
            raise ValueError("each graph candidate must be a JSON object")
        item.setdefault("candidate_id", f"candidate_{idx}")
        item.setdefault("n_agents", n_agents)
        item.setdefault("graph_type", "temporal_dag")
        graphs.append(GeneratedGraphPlan.model_validate(item))
    if not graphs:
        raise ValueError("no graph candidates returned")
    return graphs


def _validate_and_compile_candidates(
    graphs: list[GeneratedGraphPlan],
    options: GraphValidationOptions,
) -> list[_CandidateState]:
    states: list[_CandidateState] = []
    for generation_index, graph in enumerate(graphs):
        validation = validate_graph_plan(graph, options)
        repaired = graph
        repair_notes: list[str] = []
        status = "valid" if validation.valid else "rejected"
        if not validation.valid and options.repair_attempts > 0:
            repaired, repair_notes = repair_graph_plan(graph, options)
            repaired_validation = validate_graph_plan(repaired, options)
            validation = repaired_validation.model_copy(
                update={"repair_notes": repair_notes}
            )
            if repaired_validation.valid:
                status = "repaired"
        spec = None
        if validation.valid:
            spec = compile_generated_graph(repaired, options)
        protocol_steps = len(spec.steps) if spec else len(repaired.steps)
        protocol_messages = (
            sum(len(step.transmissions) for step in spec.steps)
            if spec
            else sum(len(step.edges) for step in repaired.steps)
        )
        topology_equivalence_hash = None
        exact_execution_hash = None
        canonical_temporal_edges: list[tuple[int, int, int]] = []
        if spec is not None:
            fingerprint = fingerprint_protocol_spec(spec)
            topology_equivalence_hash = fingerprint.topology_equivalence_hash
            exact_execution_hash = fingerprint.exact_execution_hash
            canonical_temporal_edges = fingerprint.canonical_temporal_edges
        states.append(
            _CandidateState(
                graph=repaired,
                spec=spec,
                generation_index=generation_index,
                record=GraphCandidateRecord(
                    candidate_id=repaired.candidate_id,
                    status=status,
                    graph_plan=repaired.model_dump(mode="json"),
                    protocol_spec=spec.model_dump(mode="json") if spec else None,
                    validation_errors=validation.errors,
                    validation_warnings=validation.warnings,
                    repair_notes=repair_notes,
                    protocol_steps=protocol_steps,
                    protocol_messages=protocol_messages,
                    selected_primary=repaired.selected_primary,
                    topology_equivalence_hash=topology_equivalence_hash,
                    exact_execution_hash=exact_execution_hash,
                    canonical_temporal_edges=canonical_temporal_edges,
                ),
            )
        )
    return states


def _dedupe_equivalent_candidates(
    states: list[_CandidateState],
) -> list[_CandidateState]:
    """Skip duplicate equivalent candidates before expensive probe evaluation."""
    grouped: dict[str, list[_CandidateState]] = {}
    representatives: list[_CandidateState] = []
    for state in states:
        key = state.record.topology_equivalence_hash
        if (
            key is None
            or state.spec is None
            or state.record.status not in {"valid", "repaired"}
        ):
            representatives.append(state)
            continue
        grouped.setdefault(key, []).append(state)

    for group in grouped.values():
        if len(group) == 1:
            representatives.append(group[0])
            continue
        representative = min(group, key=_candidate_dedup_sort_key)
        representatives.append(representative)
        for duplicate in group:
            if duplicate is representative:
                continue
            duplicate.record.status = "duplicate_equivalent_topology"
            duplicate.record.duplicate_of_candidate_id = representative.record.candidate_id
            duplicate.record.validation_warnings = [
                *duplicate.record.validation_warnings,
                (
                    "duplicate equivalent topology of "
                    f"{representative.record.candidate_id}; skipped probe evaluation"
                ),
            ]

    representatives.sort(key=lambda state: state.generation_index)
    return representatives


def _candidate_dedup_sort_key(state: _CandidateState) -> tuple[int, int, int, str, int]:
    return (
        0 if state.record.status == "valid" else 1,
        state.record.protocol_messages,
        state.record.protocol_steps,
        state.record.candidate_id,
        state.generation_index,
    )


def _select_candidate(
    valid_states: list[_CandidateState],
    runtime: MASRuntimeConfig,
) -> _CandidateState:
    """Pick the winning candidate, optionally applying the motif credit prior.

    ``valid_states`` arrives already in selection order: in ``topk`` mode it has
    been probe-evaluated and sorted by ``objective_score`` (higher = better); in
    the default single mode it is generation order, so ``valid_states[0]`` is
    today's first-valid pick.

    Default behavior (``use_motif_prior`` off, or ``motif_stats`` empty/None) is
    unchanged: the head of ``valid_states`` is returned, so selection stays
    byte-identical to before this prior existed.

    When ``use_motif_prior`` is on AND ``motif_stats`` is non-empty, this is the
    activation point for the Plan 3 Part G machinery: each valid compiled
    candidate is scored by :func:`exp_graph.mas.motifs.score_spec_by_motifs`
    (a lower-is-better predicted loss, transferred structurally from past
    evidence via shared motifs). Candidates are then stably re-sorted by that
    predicted loss ascending. The sort is stable over the incoming order, so the
    motif prior *blends* with any existing probe ``objective_score`` ordering:
    among candidates with an equal (or absent) motif signal, the prior
    probe-sorted / generation order is preserved as a deterministic tiebreak.
    Candidates that share no known motif key receive the +inf high-uncertainty
    sentinel and therefore never displace a candidate with real motif evidence;
    if *no* candidate has a known motif (all +inf), the order is unchanged.
    """
    if not runtime.use_motif_prior or not runtime.motif_stats:
        return valid_states[0]
    motif_stats = runtime.motif_stats
    scored: list[tuple[float, int, _CandidateState]] = []
    for rank, state in enumerate(valid_states):
        if state.spec is None:
            predicted = float("inf")
        else:
            predicted = score_spec_by_motifs(state.spec, motif_stats)
        # ``rank`` is the deterministic tiebreak that preserves the incoming
        # probe-sorted / generation order on equal (or +inf) motif scores.
        scored.append((predicted, rank, state))
    scored.sort(key=lambda item: (item[0], item[1]))
    return scored[0][2]


def _evaluate_candidates(
    *,
    states: list[_CandidateState],
    request: PlannerRequest,
    runtime: MASRuntimeConfig,
    seed: int,
    task_adapter: CountFrequencyTaskAdapter,
    output_dir: Path,
) -> None:
    # Probe-evaluation (topk mode only): execute each candidate on the
    # validation seeds and record an ``objective_score`` used to sort here. The
    # structural-motif credit prior (Plan 3 Part G) is applied separately and
    # opt-in in ``_select_candidate`` after this sort, so it blends with these
    # probe scores without changing the default-off ordering.
    output_dir.mkdir(parents=True, exist_ok=True)
    validation_seeds = runtime.graph_validation_seeds or [seed]
    for state in states:
        if state.spec is None:
            continue
        probe_rows: list[dict[str, object]] = []
        for probe_seed in validation_seeds:
            global_task = task_adapter.build_global_task(
                array_size=request.array_size or 64,
                value_min=runtime.value_min,
                value_max=runtime.value_max,
                seed=int(probe_seed),
            )
            soldier_llm = resolve_role_llm_config(runtime, "soldier")
            config = ProtocolRunnerConfig(
                topology_name=f"generated:{state.graph.name}",
                n_agents=request.n_agents,
                seed=int(probe_seed),
                model_name=soldier_llm.model_name,
                merge_mode=request.merge_mode,  # type: ignore[arg-type]
                init_mode=request.init_mode,  # type: ignore[arg-type]
                llm_provider=soldier_llm.platform,
                temperature=soldier_llm.temperature,
                json_retry_attempts=runtime.json_retry_attempts,
                allow_deterministic_repair=runtime.allow_deterministic_repair,
                max_parallel_agents=runtime.max_parallel_agents,
                trace_enabled=False,
                retain_traces=False,
                verbose_events=False,
                protocol_spec=state.spec,
                llm_role_summary=role_llm_summary(runtime),
            )
            result = ProtocolRunner(
                config=config,
                task_adapter=task_adapter,
                global_task=global_task,
                llm_client=(
                    create_role_llm_client(runtime, "soldier")
                    if _request_needs_soldier_llm(request)
                    else None
                ),
            ).run()
            row = _probe_row(result, request.objective.name)
            probe_rows.append(row)
            _write_json(
                output_dir / state.graph.candidate_id / f"seed_{probe_seed}.json",
                {
                    "candidate_id": state.graph.candidate_id,
                    "seed": probe_seed,
                    "summary": result.to_summary_dict(),
                    "objective_row": row,
                },
            )
        aggregate = _aggregate_probe_rows(probe_rows, request.objective.name)
        state.record.probe_scores = probe_rows
        state.record.objective_score = _objective_score(
            aggregate,
            score_mode=runtime.graph_candidate_score_mode,
        )
        state.record.score_mode = runtime.graph_candidate_score_mode
        if state.record.status in {"valid", "repaired"}:
            state.record.status = "evaluated"


def _request_needs_soldier_llm(request: PlannerRequest) -> bool:
    return request.init_mode == "llm_local_solve" or request.merge_mode != "deterministic"


def _probe_row(result: ProtocolExperimentResult, objective: str) -> dict[str, object]:
    summary = result.to_summary_dict()
    return {
        "objective": objective,
        "mean_rmse": float(summary["FinalRMSE"]),
        "exact_match_rate": 1.0 if summary["FinalExactMatch"] else 0.0,
        "mean_messages": float(summary["TotalMessages"]),
        "mean_model_calls": float(summary["TotalModelCalls"]),
        "mean_token_cost": float(
            summary["TotalPromptTokens"] + summary["TotalCompletionTokens"]
        ),
    }


def _aggregate_probe_rows(rows: list[dict[str, object]], objective: str) -> dict[str, object]:
    return {
        "objective": objective,
        "mean_rmse": _mean(rows, "mean_rmse"),
        "exact_match_rate": _mean(rows, "exact_match_rate"),
        "mean_messages": _mean(rows, "mean_messages"),
        "mean_model_calls": _mean(rows, "mean_model_calls"),
        "mean_token_cost": _mean(rows, "mean_token_cost"),
    }


def _mas_plan_from_graph(graph: GeneratedGraphPlan, spec: ProtocolGraphSpec) -> MASPlan:
    return MASPlan(
        planner_mode="graph_generate",
        topology_name=f"generated:{graph.name}",
        skill_id=None,
        operators=["llm_generate_dag"],
        protocol_spec=spec,
        config_overrides={"protocol_spec": spec},
        score=0.0,
        score_breakdown={},
        fallback_skill_id=None,
        rationale=graph.rationale or f"Generated temporal DAG {graph.name}.",
    )


def _fallback_operator_plan(
    request: PlannerRequest,
    skill_bank: SkillBank,
    reason: str,
) -> MASPlan:
    fallback_request = request.model_copy(update={"planner_mode": "operator_compose"})
    try:
        plan = EmperorPlanner(skill_bank).operator_compose.plan(fallback_request)
    except Exception:
        operators = ["local_solve", "tree_reduce"]
        spec = compose_protocol_from_operators(
            name=f"fallback_tree_{request.n_agents}",
            n_agents=request.n_agents,
            operators=operators,
            max_messages=request.budget.max_messages,
        )
        plan = MASPlan(
            planner_mode="operator_compose",
            topology_name="tree",
            operators=operators,
            protocol_spec=spec,
            config_overrides={"protocol_spec": spec},
        )
    return plan.model_copy(
        update={
            "rationale": f"{plan.rationale} [free-graph-fallback: {reason}]",
        }
    )


def _fake_graph_candidates(
    request: PlannerRequest,
    count: int,
) -> list[GeneratedGraphPlan]:
    builders = [_fake_tree_graph, _fake_star_graph, _fake_chain_graph, _fake_pair_star_graph]
    graphs = []
    for idx in range(count):
        graph = builders[idx % len(builders)](request.n_agents, idx)
        graphs.append(graph)
    return graphs


def _fake_tree_graph(n_agents: int, idx: int) -> GeneratedGraphPlan:
    steps: list[GeneratedGraphStep] = []
    stride = 1
    while stride < n_agents:
        edges = []
        block = stride * 2
        for start in range(0, n_agents, block):
            left = start + stride - 1
            right = min(start + block - 1, n_agents - 1)
            if left < n_agents and left != right:
                edges.append((left, right))
        if edges:
            steps.append(
                GeneratedGraphStep(
                    description=f"tree reduce stride {stride}",
                    edges=edges,
                    operator_hint="tree_reduce",
                )
            )
        stride *= 2
    return GeneratedGraphPlan(
        candidate_id=f"candidate_{idx}",
        name=f"generated_tree_reduce_n{n_agents}",
        n_agents=n_agents,
        steps=steps,
        selected_primary=n_agents - 1,
        rationale="Sparse tree reduction generated by fake emperor.",
        fallback_topology="tree",
    )


def _fake_star_graph(n_agents: int, idx: int) -> GeneratedGraphPlan:
    sink = n_agents - 1
    return GeneratedGraphPlan(
        candidate_id=f"candidate_{idx}",
        name=f"generated_star_sink_n{n_agents}",
        n_agents=n_agents,
        steps=[
            GeneratedGraphStep(
                description="star gather to final sink",
                edges=[(agent, sink) for agent in range(n_agents) if agent != sink],
                operator_hint="star_sink",
            )
        ],
        selected_primary=sink,
        rationale="Single-step sink gather generated by fake emperor.",
        fallback_topology="star",
    )


def _fake_chain_graph(n_agents: int, idx: int) -> GeneratedGraphPlan:
    return GeneratedGraphPlan(
        candidate_id=f"candidate_{idx}",
        name=f"generated_chain_n{n_agents}",
        n_agents=n_agents,
        steps=[
            GeneratedGraphStep(
                description=f"chain hop {agent}",
                edges=[(agent, agent + 1)],
                operator_hint="peer_propagate",
            )
            for agent in range(max(0, n_agents - 1))
        ],
        selected_primary=n_agents - 1,
        rationale="Sequential chain generated by fake emperor.",
        fallback_topology="chain",
    )


def _fake_pair_star_graph(n_agents: int, idx: int) -> GeneratedGraphPlan:
    sink = n_agents - 1
    pair_edges = [
        (agent, min(agent + 1, sink))
        for agent in range(0, n_agents - 1, 2)
        if agent != min(agent + 1, sink)
    ]
    sink_edges = [
        (agent, sink)
        for agent in range(n_agents)
        if agent != sink and agent % 2 == 1
    ]
    steps = []
    if pair_edges:
        steps.append(
            GeneratedGraphStep(
                description="pairwise local exchange",
                edges=pair_edges,
                operator_hint="peer_propagate",
            )
        )
    if sink_edges:
        steps.append(
            GeneratedGraphStep(
                description="paired representatives gather to sink",
                edges=sink_edges,
                operator_hint="star_sink",
            )
        )
    return GeneratedGraphPlan(
        candidate_id=f"candidate_{idx}",
        name=f"generated_pair_star_n{n_agents}",
        n_agents=n_agents,
        steps=steps,
        selected_primary=sink,
        rationale="Pairwise exchange followed by sink gather.",
        fallback_topology="one_peer_exponential_dag_star",
    )


def _write_graph_artifacts(
    *,
    output_dir: Path,
    records: list[GraphCandidateRecord],
    selected: GraphCandidateRecord | None,
    raw_responses: list[str],
    fallback_reason: str | None = None,
    top_k: int = 1,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    payload = [record.model_dump(mode="json") for record in records]
    _write_json(output_dir / "generated_graph_candidates.json", payload)
    _write_json(
        output_dir / "selected_graph_plan.json",
        selected.model_dump(mode="json") if selected is not None else {},
    )
    _write_json(
        output_dir / "graph_validation_summary.json",
        {
            "candidate_count": len(records),
            "rejected_candidate_count": sum(
                1 for record in records if record.status == "rejected"
            ),
            "duplicate_equivalent_candidate_count": sum(
                1
                for record in records
                if record.status == "duplicate_equivalent_topology"
            ),
            "duplicate_equivalent_groups": _duplicate_equivalent_groups(records),
            "selected_candidate_id": selected.candidate_id if selected else None,
            "selected_candidate_score": selected.objective_score if selected else None,
            "candidate_score_mode": selected.score_mode if selected else None,
            "top_k_candidate_ids": [
                record.candidate_id for record in _top_k_records(records, top_k)
            ],
            "fallback_reason": fallback_reason,
            "raw_response_count": len(raw_responses),
            "created_at": datetime.now(UTC).replace(microsecond=0).isoformat(),
        },
    )
    (output_dir / "generated_graph_candidates.md").write_text(
        _format_graph_candidates(records, selected, fallback_reason),
        encoding="utf-8",
    )


def _format_graph_candidates(
    records: list[GraphCandidateRecord],
    selected: GraphCandidateRecord | None,
    fallback_reason: str | None,
) -> str:
    lines = ["# Generated Graph Candidates", ""]
    if fallback_reason:
        lines.extend(["fallback_reason:", f"  {fallback_reason}", ""])
    lines.append(f"selected_candidate_id: {selected.candidate_id if selected else 'none'}")
    lines.append("")
    for record in records:
        lines.extend(
            [
                f"## {record.candidate_id}",
                "",
                f"status: {record.status}",
                f"steps: {record.protocol_steps}",
                f"messages: {record.protocol_messages}",
                f"selected_primary: {record.selected_primary}",
                f"objective_score: {record.objective_score}",
                f"score_mode: {record.score_mode}",
                f"topology_equivalence_hash: {record.topology_equivalence_hash}",
                f"duplicate_of_candidate_id: {record.duplicate_of_candidate_id}",
                "",
            ]
        )
        if record.validation_errors:
            lines.append("validation_errors:")
            lines.extend(f"- {item}" for item in record.validation_errors)
            lines.append("")
        if record.repair_notes:
            lines.append("repair_notes:")
            lines.extend(f"- {item}" for item in record.repair_notes)
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _duplicate_equivalent_groups(
    records: list[GraphCandidateRecord],
) -> list[dict[str, object]]:
    grouped: dict[str, list[GraphCandidateRecord]] = {}
    for record in records:
        if record.topology_equivalence_hash:
            grouped.setdefault(record.topology_equivalence_hash, []).append(record)
    groups = []
    for topology_hash, items in sorted(grouped.items()):
        duplicates = [
            item
            for item in items
            if item.status == "duplicate_equivalent_topology"
        ]
        if not duplicates:
            continue
        kept = next(
            (item.duplicate_of_candidate_id for item in duplicates if item.duplicate_of_candidate_id),
            None,
        )
        groups.append(
            {
                "topology_equivalence_hash": topology_hash,
                "kept_candidate_id": kept,
                "duplicate_candidate_ids": [item.candidate_id for item in duplicates],
            }
        )
    return groups


def _top_k_records(
    records: list[GraphCandidateRecord],
    top_k: int,
) -> list[GraphCandidateRecord]:
    selectable = [
        record
        for record in records
        if record.status in {"selected", "evaluated", "valid", "repaired"}
    ]
    selectable.sort(
        key=lambda record: record.objective_score
        if record.objective_score is not None
        else float("-inf"),
        reverse=True,
    )
    return selectable[: max(1, top_k)]


def _add_reachability_warnings(graph: GeneratedGraphPlan, warnings: list[str]) -> None:
    selected = graph.selected_primary
    if selected is None:
        return
    reachable: dict[int, set[int]] = {
        agent: {agent} for agent in range(graph.n_agents)
    }
    for step in graph.steps:
        updates = {agent: set(values) for agent, values in reachable.items()}
        for src, dst in step.edges:
            if src not in reachable or dst not in updates:
                continue
            updates[dst].update(reachable.get(src, {src}))
        reachable = updates
    missing = sorted(set(range(graph.n_agents)) - reachable.get(selected, set()))
    if missing:
        warnings.append(
            f"agents without temporal path to selected_primary {selected}: {missing}"
        )


def _skill_context(skill: SkillCard) -> dict[str, object]:
    return {
        "skill_id": skill.skill_id,
        "version": skill.version,
        "objective": skill.objective,
        "organization_policy": skill.organization_policy,
        "expected_tradeoff": skill.expected_tradeoff,
        "expected_dynamics": skill.expected_dynamics,
        "design_insights": skill.design_insights[-6:],
        "risk_notes": skill.risk_notes[-4:],
        "fallback": skill.fallback,
    }


def _loads_json_object(text: str) -> dict[str, Any]:
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", text, flags=re.DOTALL)
        if not match:
            raise
        data = json.loads(match.group(0))
    if not isinstance(data, dict):
        raise ValueError("expected JSON object")
    return data


def _mean(rows: list[dict[str, object]], key: str) -> float:
    values = [float(row[key]) for row in rows if row.get(key) is not None]
    return fmean(values) if values else 0.0


def _objective_score(
    row: dict[str, object],
    *,
    score_mode: str = "objective",
) -> float:
    rmse = float(row.get("mean_rmse", 0.0))
    if score_mode == "accuracy_max":
        return -rmse
    objective = str(row.get("objective", "balanced"))
    messages = float(row.get("mean_messages", 0.0))
    tokens = float(row.get("mean_token_cost", 0.0))
    exact = float(row.get("exact_match_rate", 0.0))
    if objective == "budget_first":
        return exact - 0.4 * rmse - 0.02 * messages - 0.0001 * tokens
    if objective == "accuracy_first":
        return exact - rmse - 0.002 * messages - 0.00001 * tokens
    return exact - 0.7 * rmse - 0.01 * messages - 0.00005 * tokens


def _write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
